### ISSUE TITLE
Interact.jl not working

### ISSUE THREAD

**Issue by currymj** [JuliaIDE/Julia-LT#171]
On trying to execute "using Interact" in Juno (OS X 10.10, using the bundle version), I get this error in the console:

```
Invalid behavior: :lt.objs.langs.julia/commands
ReferenceError: jQuery is not defined
    at eval (eval at eval_scripts (/Applications/Juno.app/Contents/Resources/app/plugins/Julia-LT/julia_compiled.js), <anonymous>:154:4)
    at eval (native)
    at eval_scripts (/Applications/Juno.app/Contents/Resources/app/plugins/Julia-LT/julia_compiled.js:105:63)
    at Function.__BEH__commands (/Applications/Juno.app/Contents/Resources/app/plugins/Julia-LT/julia_compiled.js:294:46)
    at c (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///Applications/Juno.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20492:14)
```

Something gets loaded, because the `@manipulate` macro does show up in autocomplete, but actually trying to use it produces similar error messages.

It would be nice to be able to `@manipulate` things in Juno; and it seems like it ought to be possible, given that Gadfly plots are already interactive. I don't know if this is just a bug or really a feature request, or if the problem is that Interact.jl is only built to be used in IJulia.

**Comment by one-more-minute** [comment]
I think Interact.jl is pretty IJulia specific at the moment (though it could work in Juno in principle), so fixing this specific error probably won't help all that much. cc @shashi

**Comment by filipstachura** [comment]
Are there any plans on getting support for Interact into Juno? Would connecting IJulia to Juno help in any way (http://junolab.org/docs/terminal.html)?

**Comment by Varanas** [comment]
Well, kinda. Development of Juno has pretty much switched over to [Juno/Atom](https://github.com/JunoLab/atom-julia-client), so in the long run there are/should be plans to support Interact. 
First task is to get feature parity with Juno/LT, though,
